name: johnsonville_cost_simulator
description: "Johnsonville Cost Simulator"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  animated_flip_counter: ^0.3.4
  animations: ^2.0.11
  auto_injector: ^2.0.5
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  custom_pop_up_menu: ^1.2.4
  dio: ^5.6.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  gif: ^2.3.0
  flutter_bloc: ^8.1.6
  flutter_calendar_carousel: ^2.4.3
  flutter_dotenv: 5.1.0
  flutter_slider_indicator: ^1.0.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10
  flutter_to_pdf: ^0.2.2
  fluttertoast: ^8.2.8
  g_recaptcha_v3: ^0.0.6
  gap: ^3.0.1
  go_router: ^14.2.3
  intl: ^0.18.0
  jumping_dot: ^0.0.7
  logger: ^2.4.0

  motion_toast: ^2.11.0
  neopop: ^1.0.2
  open_file: ^3.5.4
  path_provider: ^2.1.4
  pdf: ^3.11.1
  printing: ^5.13.2
  responsive_builder: ^0.7.1
  shared_preferences: ^2.3.1
  shimmer: ^3.0.0
  shimmer_animation: ^2.2.1
  universal_html: ^2.2.4
  url_launcher: ^6.3.0
  lottie: ^3.1.3
  dotted_border: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/.env_dev

  fonts:
    - family: Tablet Gothic
      fonts:
        - asset: assets/fonts/tablet-gothic/TabletGothicNarrowEb.ttf
          weight: 800
        - asset: assets/fonts/tablet-gothic/TabletGothicNarrow-Bold.ttf
          weight: 700
        - asset: assets/fonts/tablet-gothic/TabletGothicNarrowSb.ttf
          weight: 600
        - asset: assets/fonts/tablet-gothic/TabletGothicNarrow.ttf
          weight: 500
        - asset: assets/fonts/tablet-gothic/TabletGothicNarrowLt.ttf
          weight: 400
        - asset: assets/fonts/tablet-gothic/TabletGothicNarrowTh.ttf
          weight: 300
    - family: Prequel Bold
      fonts:
        - asset: assets/fonts/Prequel-Bold.ttf
          weight: 900
